app = "cosmogenesis-learning-engine"
primary_region = "iad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services.http_checks]]
  path = "/core/health-check.html"
  interval = "30s"
  timeout  = "2s"

