# netlify.toml — single build block, LFS enabled, one redirect, minimal security headers

[build]
  publish = "site"
  command = ""

  # Enable Git LFS assets on Netlify (Large Media or standard LFS support)
  [build.environment]
    GIT_LFS_ENABLED = "true"

# Keep the heavy app available under /engine (adjust target if needed)
[[redirects]]
  from = "/engine/*"
  to   = "/index.html"
  status = 200

# Minimal, sane security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options        = "SAMEORIGIN"
    Referrer-Policy        = "no-referrer"
    Permissions-Policy     = "accelerometer=(), camera=(), geolocation()"
