# cosmogenesis-learning-engine / Netlify configuration
# Brain: serves small shared datasets + optional hero asset.
[build]
  command = ""
  publish = "/"

[build.environment]
  GIT_LFS_ENABLED = "false"

# Allow spokes to fetch shared data with permissive CORS and sensible caching.
[[headers]]
  for = "/data/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cache-Control = "public, max-age=3600, must-revalidate"
    Content-Type = "application/json; charset=utf-8"

# Minimal security headers for the landing page or any ancillary files.
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=()"
    Content-Type = "text/html; charset=UTF-8"

# Explicit content-types for primary static assets to remain ND-safe and predictable offline.
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=UTF-8"
