# /netlify.toml
[build]
  publish = "site"
  command = ""

# keep your older app under /engine if needed
[[redirects]]
  from = "/engine/*"
  to = "/app/index.html"
  status = 200 # /netlify.toml
[build]
  publish = "site"
  command = ""

# keep your older app under /engine if needed
[[redirects]]
  from = "/engine/*"
  to = "/app/index.html"
  status = 200
