  name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # use the same version you run locally

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system packages for Pillow
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libjpeg-turbo8-dev \
            zlib1g-dev \
            libpng-dev \
            libfreetype6-dev \
            liblcms2-dev \
            libtiff5-dev \
            libwebp-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libopenjp2-7-dev

      - name: Install dependencies
        env:
          PIP_PREFER_BINARY: "1"
        run: |
          python -m pip install --upgrade pip
          pip install --only-binary=:all: -r requirements.txt || pip install -r requirements.txt

      - name: Verify Pillow
        run: |
          python - << 'PY'
          import PIL
          from PIL import Image
          print("Pillow:", PIL.__version__)
          print("OK:", bool(Image))
          PY

      # - name: Run tests
      #   run: pytest -q
