name: CI

on:
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  build:
    name: Lint • Generate Assets • Verify
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout (with LFS for audio)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      # ---------------- Python (optional) ----------------
      - name: Set up Python
        if: ${{ hashFiles('**/*.py') != '' }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        if: ${{ hashFiles('**/*.py') != '' }}
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system packages for Pillow (only if Python present)
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libjpeg-turbo8-dev \
            zlib1g-dev \
            lib